// Example sketches — all use setup()/draw() pattern (no fn main needed)
export const EXAMPLES = [
  {
    name: "Hello MoonBit",
    code: [
      '// ━━ はじめてのスケッチ ━━',
      '// setup() でキャンバス作成、draw() で毎フレーム描画。',
      '// Processing/p5.js と同じパターン！',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.02',
      '  background(30, 30, 46)',
      '',
      '  // range for — MoonBitの簡潔なループ',
      '  for i in 0..<12 {',
      '    let fi = i.to_double()',
      '    let angle = t + fi * tau / 12.0',
      '    let x = 200.0 + cos(angle) * 120.0',
      '    let y = 200.0 + sin(angle) * 120.0',
      '    let sz = 10.0 + (sin(t + fi * 0.5) + 1.0) * 20.0',
      '    let r = ((sin(t + fi * 0.3) + 1.0) * 127.0).to_int()',
      '    let g = ((cos(t + fi * 0.5) + 1.0) * 127.0).to_int()',
      '    set_fill_style(rgba(r, g, 200, 0.8))',
      '    circle(x, y, sz)',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Enum & Match",
    code: [
      '// ━━ Enum (代数的データ型) & パターンマッチ ━━',
      '// MoonBitのenumはRustのenumに似た直和型。',
      '// 各バリアントが異なるデータを持てる。',
      '',
      'enum Shape {',
      '  Circle(Vec2, Double)',
      '  Rect(Vec2, Double, Double)',
      '  Tri(Vec2, Vec2, Vec2)',
      '}',
      '',
      '// match式 — 全バリアントを網羅しないとコンパイルエラー',
      'fn draw_shape(shape : Shape, color : String) -> Unit {',
      '  set_fill_style(color)',
      '  match shape {',
      '    Circle(c, r) => {',
      '      begin_path()',
      '      arc(c.x, c.y, r, 0.0, tau)',
      '      fill()',
      '    }',
      '    Rect(p, w, h) => fill_rect(p.x, p.y, w, h)',
      '    Tri(a, b, c) => {',
      '      begin_path()',
      '      move_to(a.x, a.y)',
      '      line_to(b.x, b.y)',
      '      line_to(c.x, c.y)',
      '      close_path()',
      '      fill()',
      '    }',
      '  }',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.02',
      '  background(25, 25, 45)',
      '  let shapes : Array[(Shape, String)] = [',
      '    (Circle(Vec2::new(200.0 + cos(t) * 80.0, 150.0), 30.0 + sin(t * 2.0) * 10.0),',
      '     rgba(255, 100, 150, 0.8)),',
      '    (Rect(Vec2::new(100.0 + sin(t * 0.7) * 50.0, 250.0), 80.0, 60.0),',
      '     rgba(100, 200, 255, 0.8)),',
      '    (Tri(Vec2::new(300.0, 280.0 + sin(t) * 20.0),',
      '         Vec2::new(260.0, 350.0), Vec2::new(340.0, 350.0)),',
      '     rgba(150, 255, 100, 0.8)),',
      '  ]',
      '  for pair in shapes {',
      '    let (shape, color) = pair',
      '    draw_shape(shape, color)',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Struct & Method",
    code: [
      '// ━━ Struct & メソッド ━━',
      '// 構造体にメソッドを定義。',
      '// タプル型 (Int, Int, Int) でRGBを表現。',
      '',
      'struct Particle {',
      '  mut pos : Vec2',
      '  mut vel : Vec2',
      '  color : (Int, Int, Int)',
      '  size : Double',
      '}',
      '',
      'fn Particle::update(self : Particle) -> Unit {',
      '  self.pos = self.pos.add(self.vel)',
      '  if self.pos.x < 0.0 || self.pos.x > 400.0 {',
      '    self.vel = { x: -self.vel.x, y: self.vel.y }',
      '  }',
      '  if self.pos.y < 0.0 || self.pos.y > 400.0 {',
      '    self.vel = { x: self.vel.x, y: -self.vel.y }',
      '  }',
      '}',
      '',
      'fn Particle::draw(self : Particle) -> Unit {',
      '  let (r, g, b) = self.color  // タプル分解',
      '  set_fill_style(rgba(r, g, b, 0.7))',
      '  circle(self.pos.x, self.pos.y, self.size)',
      '}',
      '',
      'let particles : Array[Particle] = {',
      '  let arr : Array[Particle] = []',
      '  for i in 0..<30 {',
      '    let fi = i.to_double()',
      '    let angle = fi * 0.618 * tau',
      '    arr.push({',
      '      pos: Vec2::new(200.0, 200.0),',
      '      vel: Vec2::new(cos(angle) * (1.0 + fi * 0.1), sin(angle) * (1.0 + fi * 0.1)),',
      '      color: (((fi * 17.0 + 100.0) % 255.0).to_int(), ((fi * 31.0 + 50.0) % 255.0).to_int(), 200),',
      '      size: 4.0 + fi * 0.3,',
      '    })',
      '  }',
      '  arr',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  background_a(25, 25, 45, 0.15)',
      '  for p in particles {',
      '    p.update()',
      '    p.draw()',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Functional Loop",
    code: [
      '// ━━ 関数型 for ループ ━━',
      '// 状態を引数に取り continue で更新。',
      '// nobreak で最終値を返す。Rustにない独自機能！',
      '',
      'fn hsv_to_rgb(h : Double, s : Double, v : Double) -> (Int, Int, Int) {',
      '  let c = v * s',
      '  let x = c * (1.0 - abs_double((h / 60.0) % 2.0 - 1.0))',
      '  let m = v - c',
      '  let (r1, g1, b1) = if h < 60.0 { (c, x, 0.0) }',
      '    else if h < 120.0 { (x, c, 0.0) }',
      '    else if h < 180.0 { (0.0, c, x) }',
      '    else if h < 240.0 { (0.0, x, c) }',
      '    else if h < 300.0 { (x, 0.0, c) }',
      '    else { (c, 0.0, x) }',
      '  (((r1 + m) * 255.0).to_int(), ((g1 + m) * 255.0).to_int(), ((b1 + m) * 255.0).to_int())',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.5',
      '  background(15, 15, 30)',
      '  // 関数型 for: 黄金角スパイラル',
      '  for i = 0, angle = 0.0; i < 500; {',
      '    let radius = i.to_double() * 0.4',
      '    let x = 200.0 + cos(angle + t * 0.01) * radius',
      '    let y = 200.0 + sin(angle + t * 0.01) * radius',
      '    if x > 0.0 && x < 400.0 && y > 0.0 && y < 400.0 {',
      '      let hue = (i.to_double() * 0.7 + t) % 360.0',
      '      let (r, g, b) = hsv_to_rgb(hue, 0.8, 1.0)',
      '      set_fill_style(rgba(r, g, b, 0.8))',
      '      let sz = 2.0 + sin(i.to_double() * 0.05 + t * 0.02) * 2.0',
      '      circle(x, y, sz)',
      '    }',
      '    continue i + 1, angle + 2.39996  // 黄金角',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Option & Guard",
    code: [
      '// ━━ Option型 & guard文 ━━',
      '// Option[T] で null安全。guard で早期スキップ。',
      '',
      'struct Star {',
      '  pos : Vec2',
      '  speed : Double',
      '  bright : Double',
      '  hue : Double',
      '}',
      '',
      'let stars : Array[Star] = {',
      '  let arr : Array[Star] = []',
      '  for i in 0..<80 {',
      '    let fi = i.to_double()',
      '    arr.push({ pos: Vec2::new(random_double() * 400.0, random_double() * 400.0),',
      '      speed: 0.5 + random_double() * 2.0,',
      '      bright: 0.3 + random_double() * 0.7,',
      '      hue: fi * 37.0 % 360.0 })',
      '  }',
      '  arr',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.01',
      '  background_a(10, 10, 25, 0.1)',
      '  // 星を描画',
      '  for star in stars {',
      '    let pulse = star.bright * (0.7 + 0.3 * sin(t * star.speed * 3.0))',
      '    let sz = 1.0 + pulse * 3.0',
      '    set_fill_style(rgba(',
      '      (200.0 + 55.0 * sin(star.hue * 0.017)).to_int(),',
      '      (200.0 + 55.0 * cos(star.hue * 0.013)).to_int(),',
      '      255, pulse))',
      '    circle(star.pos.x, star.pos.y, sz)',
      '  }',
      '  // 近い星同士を結ぶ — guard で距離チェック',
      '  for i, a in stars {',
      '    for j in (i + 1)..<stars.length() {',
      '      let b = stars[j]',
      '      let d = a.pos.dist(b.pos)',
      '      guard d < 50.0 else { continue }',
      '      let alpha = map_range(d, 0.0, 50.0, 0.4, 0.0)',
      '      set_stroke_style(rgba(150, 180, 255, alpha))',
      '      set_line_width(0.5)',
      '      draw_line(a.pos.x, a.pos.y, b.pos.x, b.pos.y)',
      '    }',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Higher-Order Fn",
    code: [
      '// ━━ 高階関数 & クロージャ ━━',
      '// 関数を引数に取る・返すのが自然にできる。',
      '',
      '// 軌道関数を返す高階関数',
      'fn make_orbit(cx : Double, cy : Double, r : Double, speed : Double) -> (Double) -> Vec2 {',
      '  fn(t : Double) -> Vec2 {',
      '    Vec2::new(cx + cos(t * speed) * r, cy + sin(t * speed) * r)',
      '  }',
      '}',
      '',
      '// 描画を装飾するコンビネータ',
      'fn with_glow(draw_fn : (Vec2, Double) -> Unit) -> (Vec2, Double) -> Unit {',
      '  fn(pos : Vec2, sz : Double) {',
      '    set_global_alpha(0.15)',
      '    draw_fn(pos, sz * 3.0)',
      '    set_global_alpha(0.9)',
      '    draw_fn(pos, sz)',
      '    set_global_alpha(1.0)',
      '  }',
      '}',
      '',
      'fn draw_dot(pos : Vec2, sz : Double) -> Unit {',
      '  circle(pos.x, pos.y, sz)',
      '}',
      '',
      'let orbits : Array[(Double) -> Vec2] = [',
      '  make_orbit(200.0, 200.0, 100.0, 1.0),',
      '  make_orbit(200.0, 200.0, 60.0, -1.7),',
      '  make_orbit(200.0, 200.0, 140.0, 0.5),',
      '  make_orbit(200.0, 200.0, 30.0, 3.0),',
      ']',
      '',
      'let colors : Array[String] = [',
      '  rgba(255, 100, 150, 1.0), rgba(100, 200, 255, 1.0),',
      '  rgba(255, 220, 100, 1.0), rgba(150, 255, 150, 1.0),',
      ']',
      '',
      'let glow_dot : (Vec2, Double) -> Unit = with_glow(draw_dot)',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.02',
      '  background_a(15, 10, 30, 0.08)',
      '  // 軌跡を描画',
      '  for i, orbit_fn in orbits {',
      '    set_stroke_style(colors[i])',
      '    set_line_width(0.3)',
      '    begin_path()',
      '    for j in 0..<200 {',
      '      let p = orbit_fn(t - j.to_double() * 0.02)',
      '      if j == 0 { move_to(p.x, p.y) } else { line_to(p.x, p.y) }',
      '    }',
      '    stroke_path()',
      '  }',
      '  // グロー付きで現在位置を描画',
      '  for i, orbit_fn in orbits {',
      '    set_fill_style(colors[i])',
      '    glow_dot(orbit_fn(t), 5.0)',
      '  }',
      '}',
    ].join('\n'),
  },
  {
    name: "Labeled Args",
    code: [
      '// ━━ ラベル付き引数 & デフォルト値 ━━',
      '// 名前付きで呼べるので可読性が高い。',
      '',
      'fn draw_ring(',
      '  center~ : Vec2,',
      '  radius~ : Double,',
      '  thickness~ : Double = 2.0,',
      '  segments~ : Int = 60,',
      '  color~ : String = "white",',
      '  dash~ : Double = 1.0,',
      ') -> Unit {',
      '  set_stroke_style(color)',
      '  set_line_width(thickness)',
      '  for i in 0..<segments {',
      '    let ratio = i.to_double() / segments.to_double()',
      '    if ratio % 0.1 > dash * 0.1 { continue }',
      '    let a1 = ratio * tau',
      '    let a2 = (i.to_double() + 1.0) / segments.to_double() * tau',
      '    begin_path()',
      '    arc(center.x, center.y, radius, a1, a2)',
      '    stroke_path()',
      '  }',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let t = frame_count().to_double() * 0.01',
      '  background(15, 15, 35)',
      '  let c = Vec2::new(200.0, 200.0)',
      '  // ラベル付き引数で意味が明確',
      '  draw_ring(center=c, radius=150.0,',
      '    thickness=1.0, color=rgba(100, 150, 255, 0.3))',
      '  draw_ring(center=c, radius=120.0,',
      '    thickness=2.0, segments=30,',
      '    color=rgba(255, 150, 100, 0.5),',
      '    dash=sin(t) * 0.5 + 0.5)',
      '  draw_ring(center=c, radius=80.0,',
      '    thickness=3.0, segments=12,',
      '    color=rgba(100, 255, 200, 0.7),',
      '    dash=cos(t * 0.7) * 0.5 + 0.5)',
      '  draw_ring(center=c, radius=40.0,',
      '    thickness=4.0, segments=6,',
      '    color=rgba(255, 255, 100, 0.9),',
      '    dash=sin(t * 1.5) * 0.5 + 0.5)',
      '  // 中心点',
      '  set_fill_style("white")',
      '  circle(200.0, 200.0, 6.0)',
      '}',
    ].join('\n'),
  },
  {
    name: "Mouse Drawing",
    code: [
      '// ━━ マウスで描画 ━━',
      '// マウスを押しながら動かすと描ける簡単ペイントアプリ。',
      '// mouse_x(), mouse_y(), mouse_is_pressed() を使用。',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '  background(25, 25, 45)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  let mx = mouse_x().to_double()',
      '  let my = mouse_y().to_double()',
      '  let t = frame_count().to_double() * 0.02',
      '',
      '  // マウスが押されていたら描画',
      '  if mouse_is_pressed() {',
      '    let hue = (t * 50.0) % 360.0',
      '    let r = ((sin(hue * 0.017) + 1.0) * 127.0).to_int()',
      '    let g = ((sin(hue * 0.017 + 2.0) + 1.0) * 127.0).to_int()',
      '    let b = ((sin(hue * 0.017 + 4.0) + 1.0) * 127.0).to_int()',
      '    set_fill_style(rgba(r, g, b, 0.8))',
      '    circle(mx, my, 12.0)',
      '    // 周囲に小さなドットを散らす',
      '    for i in 0..<5 {',
      '      let angle = random_double() * tau',
      '      let dist = random_double() * 20.0',
      '      let px = mx + cos(angle) * dist',
      '      let py = my + sin(angle) * dist',
      '      set_fill_style(rgba(r, g, b, 0.4))',
      '      circle(px, py, 3.0 + random_double() * 4.0)',
      '    }',
      '  } else {',
      '    // マウスが離れている時はカーソル表示',
      '    set_stroke_style(rgba(200, 200, 255, 0.5))',
      '    set_line_width(1.0)',
      '    begin_path()',
      '    arc(mx, my, 12.0, 0.0, tau)',
      '    stroke_path()',
      '  }',
      '',
      '  // 説明テキスト',
      '  set_fill_style(rgba(200, 200, 255, 0.4))',
      '  set_font("14px sans-serif")',
      '  fill_text("Click and drag to draw", 10.0, 390.0)',
      '}',
    ].join('\n'),
  },
  {
    name: "Mouse Interaction",
    code: [
      '// ━━ マウスインタラクション ━━',
      '// パーティクルがマウスに引き寄せられる。',
      '',
      'struct Dot {',
      '  mut pos : Vec2',
      '  mut vel : Vec2',
      '  color : (Int, Int, Int)',
      '  size : Double',
      '}',
      '',
      'let dots : Array[Dot] = {',
      '  let arr : Array[Dot] = []',
      '  for i in 0..<40 {',
      '    let fi = i.to_double()',
      '    arr.push({',
      '      pos: Vec2::new(random_double() * 400.0, random_double() * 400.0),',
      '      vel: Vec2::new(0.0, 0.0),',
      '      color: (',
      '        (100.0 + fi * 3.5).to_int() % 255,',
      '        (150.0 + fi * 5.0).to_int() % 255,',
      '        255,',
      '      ),',
      '      size: 4.0 + fi * 0.2,',
      '    })',
      '  }',
      '  arr',
      '}',
      '',
      'fn setup() -> Unit {',
      '  size(400, 400)',
      '}',
      '',
      'fn draw() -> Unit {',
      '  background_a(20, 20, 40, 0.15)',
      '  let mx = mouse_x().to_double()',
      '  let my = mouse_y().to_double()',
      '  let mouse = Vec2::new(mx, my)',
      '',
      '  for dot in dots {',
      '    // マウスへのベクトル',
      '    let dx = mx - dot.pos.x',
      '    let dy = my - dot.pos.y',
      '    let dist = sqrt(dx * dx + dy * dy)',
      '',
      '    // マウスが押されていたら強く引く、そうでなければ弱く',
      '    let force = if mouse_is_pressed() { 0.8 } else { 0.15 }',
      '    if dist > 1.0 {',
      '      dot.vel = {',
      '        x: dot.vel.x * 0.92 + dx / dist * force,',
      '        y: dot.vel.y * 0.92 + dy / dist * force,',
      '      }',
      '    }',
      '',
      '    // 位置更新',
      '    dot.pos = dot.pos.add(dot.vel)',
      '',
      '    // 画面端で跳ね返り',
      '    if dot.pos.x < 0.0 || dot.pos.x > 400.0 {',
      '      dot.vel = { x: -dot.vel.x * 0.5, y: dot.vel.y }',
      '    }',
      '    if dot.pos.y < 0.0 || dot.pos.y > 400.0 {',
      '      dot.vel = { x: dot.vel.x, y: -dot.vel.y * 0.5 }',
      '    }',
      '',
      '    // 描画',
      '    let (r, g, b) = dot.color',
      '    let alpha = if dist < 100.0 { 0.9 } else { 0.5 }',
      '    set_fill_style(rgba(r, g, b, alpha))',
      '    circle(dot.pos.x, dot.pos.y, dot.size)',
      '',
      '    // マウスに近いドットは線で結ぶ',
      '    if dist < 120.0 {',
      '      let line_alpha = (120.0 - dist) / 120.0 * 0.3',
      '      set_stroke_style(rgba(r, g, b, line_alpha))',
      '      set_line_width(0.5)',
      '      draw_line(dot.pos.x, dot.pos.y, mx, my)',
      '    }',
      '  }',
      '',
      '  // マウスカーソル表示',
      '  set_fill_style(rgba(255, 255, 255, 0.3))',
      '  circle(mx, my, 8.0)',
      '}',
    ].join('\n'),
  },
];
